#!/bin/bash

ACTION=$2

mkdir --parents ./_run

if [ $ACTION = status ]
then
  naught status ./_run/$1.ipc
fi

if [ $ACTION = stop ]
then
  naught stop ./_run/$1.ipc
fi

if [ $ACTION = deploy ]
then
  naught deploy ./_run/$1.ipc
fi

if [ $ACTION = start ]
then
  naught start \
	--worker-count 1 \
    --ipc-file ./_run/$1.ipc \
    --log ./_run/$1.sys.log \
    --stdout ./_run/$1.stdout.log \
    --stderr ./_run/$1.stderr.log \
    --max-log-size 10485760 \
    --cwd . \
    $1 $3
fi

